baseURL = "https://d4sein.github.io/blog/"
title = "Blog"
theme = "lekh"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  description = "Your site description"
  copyright = "Copyright Â© 2021 d4sein"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    title = "categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 4

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true